config.val: FellowSpringKawamura
management.endpoints.web.exposure.include: health
otel.logs.exporter: none
otel.traces.exporter: otlp
otel.exporter.otlp.traces.endpoint: http://host.docker.internal:55681/v1/traces
otel.metrics.exporter: otlp
otel.exporter.otlp.metrics.endpoint: http://host.docker.internal:55681/v1/metrics